### ISSUE TITLE
Notification options for Hipchat

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-contrib-hipchat#12]
Would be nice to have an option to configure what notifications are send to hipchat
(wiki created, wiki updated, issue created, issue updated, etc.)

**Comment by astagi** [comment]
Hi @florisvanwoudenberg I'm working on this :) it's a useful feature to have!

**Comment by florisvanwoudenberg** [comment]
thanks!

**Comment by astagi** [comment]
@florisvanwoudenberg sorry for my late: https://github.com/taigaio/taiga-contrib-hipchat/pull/15

**Comment by florisvanwoudenberg** [comment]
@astagi Thank you very much! I noticed #15

**Comment by astagi** [comment]
On master now :) thank you!
