### ISSUE TITLE
trying to install taiga-contrib-hipchat

### ISSUE THREAD

**Issue by aleskinen** [taigaio/taiga-contrib-hipchat#16]
After
pip install taiga-contrib-hipchat
I get
SyntaxError: Non-ASCII character '\xc3' in file taiga_contrib_hipchat/**init**.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_taiga/taiga-contrib-hipchat
Storing debug log for failure in /home/taiga/.pip/pip.log

**Comment by bameda** [comment]
Taiga only runs with python 3.

Install the plugin in the virtualenv

```
workon taiga
pip install taiga-contrib-hipchat
```

Regards
