### ISSUE TITLE
I Think there is an error in README

### ISSUE THREAD

**Issue by wojtekw92** [taigaio/taiga-contrib-hipchat#20]
In README we have command 
`svn export "https://github.com/taigaio/taiga-contrib-hipchat/tags/$(pip show taiga-contrib-hipchat | awk '/^Version: /{print $2}')/front/dist" "hipchat"`
But id doesn't work, I think it should be 
`svn export "https://github.com/taigaio/taiga-contrib-hipchat/trunk/$(pip show taiga-contrib-hipchat | awk '/^Version: /{print $2}')/front/dist" "hipchat"`

**Comment by bameda** [comment]
this is because this README file is for dev versión. Try with https://github.com/taigaio/taiga-contrib-hipchat/tree/stable
