### ISSUE TITLE
Non-ascii caracter

### ISSUE THREAD

**Issue by tboulogne** [taigaio/taiga-contrib-hipchat#7]
Hello,

Trying to setup the contrib i get

```
SyntaxError: Non-ASCII character '\xc3' in file taiga_contrib_hipchat/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

Any tip to avoid this please ?

Thanks for all.

Thierry

**Comment by superalex** [comment]
It seems you are installing the plugin with python 2.7, Taiga needs python 3.4

**Comment by tboulogne** [comment]
i think the installation documentation need some update :

```
sudo pip3 install circus
```

instead of

```
sudo pip2 install circus
```

isn't it ?

**Comment by superalex** [comment]
I don't think so, circus needs python2 for working properly
