### ISSUE TITLE
Add user to notifications

### ISSUE THREAD

**Issue by ivanoats** [taigaio/taiga-contrib-hipchat#8]
Is it possible for the bot to add who was doing the commenting?

![screenshot](https://s3.amazonaws.com/f.cl.ly/items/2L1c1Q0p0X2H2w3F2g1a/Screenshot%202015-03-27%2009.06.52.png)

e.g. who said the comment above? :arrow_up:

**Comment by astagi** [comment]
![screen shot 2015-04-04 at 14 03 58](https://cloud.githubusercontent.com/assets/537363/6992509/95549b40-dad3-11e4-8764-d6a57ad4c792.png)

**Comment by astagi** [comment]
Thank you for your suggestion :+1:
